In [7]:
import numpy as np
import pandas as pd

#loading dataset
df = pd.read_csv("cafedataset.csv")


df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [8]:
#repalcing error and unknown values with nan beacuse python understand nan values
df.replace(["ERROR", "UNKNOWN"], np.nan, inplace=True)


#converting to data formats like "2"->2 (str->int values)
df['Quantity']=pd.to_numeric(df['Quantity'],errors='coerce')
df['Price Per Unit']=pd.to_numeric(df['Price Per Unit'],errors='coerce')
df['Total Spent']=pd.to_numeric(df['Total Spent'],errors='coerce')
df['Transaction Date']=pd.to_datetime(df['Transaction Date'],errors='coerce')

#handling missing values
df['Item'].fillna(df['Item'].mode()[0])
df['Price Per Unit'].fillna(df["Price Per Unit"].mean())
df['Total Spent'].fillna(df['Total Spent'].mean())
df['Total Spent'] = df['Quantity'] * df['Price Per Unit']
df['Quantity'].fillna(df['Quantity'].median())
df['Payment Method'].fillna(df['Payment Method'].mode()[0])
df['Location'].fillna(df['Location'].mode()[0])
df['Transaction Date'].fillna(df['Transaction Date'].mode()[0])


#calculating Total Bill
df['Calculated Total'] = df['Quantity'] * df['Price Per Unit']
df['Day'] = df['Transaction Date'].dt.day_name()


print("Cleaned dataset saved successfully!")
df.head()

Cleaned dataset saved successfully!

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Calculated Total,Day
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0,Friday
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,12.0,Tuesday
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,4.0,Wednesday
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27,10.0,Thursday
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0,Sunday

In [10]:
df.to_csv('cleaned_cafe_sale.csv',index=False)